export const locationsTypes = [
  ...new Set([
    "Planet",
    "Cluster",
    "Space station",
    "Planet",
    "Microverse",
    "TV",
    "Resort",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Fantasy town",
    "Planet",
    "Space station",
    "Planet",
    "Dream",
    "Planet",
    "Planet",
    "Dimension",
    "unknown",
    "Planet",
    "Microverse",
    "Menagerie",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Game",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Customs",
    "Space station",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Daycare",
    "Planet",
    "Space station",
    "Dwarf planet (Celestial Dwarf)",
    "Planet",
    "Miniverse",
    "Teenyverse",
    "Planet",
    "Planet",
    "Box",
    "Spacecraft",
    "Planet",
    "Microverse",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Artificially generated world",
    "Machine",
    "Planet",
    "Planet",
    "Arcade",
    "unknown",
    "Planet",
    "Dream",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Spa",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Planet",
    "Space station",
    "Quadrant",
    "Quasar",
    "Mount",
    "Liquid",
    "Convention",
    "Space station",
    "Mount",
    "Woods",
    "Planet",
    "Planet",
    "Planet",
    "Space station",
    "Diegesis",
    "Non-Diegetic Alternative Reality",
    "Nightmare",
    "Diegesis",
    "Diegesis",
    "Asteroid",
    "Acid Plant",
    "Dimension",
    "Reality",
    "Death Star",
    "Planet",
    "Spacecraft",
    "Base",
    "Liquid",
    "Dimension",
    "Elemental Rings",
    "Planet",
    "Planet",
    "Human",
    "Space",
    "Hell",
    "Police Department",
    "Country",
    "Consciousness",
    "Consciousness",
    "Planet",
    "Dimension",
    "Planet",
    "Planet",
    "Memory",
  ]),
];
export const locationsDimensions = [
  ...new Set([
    "Dimension C-137",
    "unknown",
    "unknown",
    "unknown",
    "Dimension C-137",
    "unknown",
    "unknown",
    "Post-Apocalyptic Dimension",
    "Replacement Dimension",
    "unknown",
    "unknown",
    "Cronenberg Dimension",
    "unknown",
    "Fantasy Dimension",
    "unknown",
    "unknown",
    "Dimension 5-126",
    "Dimension C-137",
    "Replacement Dimension",
    "Replacement Dimension",
    "Testicle Monster Dimension",
    "Cromulon Dimension",
    "Dimension C-500A",
    "Replacement Dimension",
    "unknown",
    "Dimension K-83",
    "unknown",
    "Replacement Dimension",
    "Replacement Dimension",
    "unknown",
    "Dimension J19ζ7",
    "Replacement Dimension",
    "Eric Stoltz Mask Dimension",
    "Evil Rick's Target Dimension",
    "Replacement Dimension",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "unknown",
    "Giant Telepathic Spiders Dimension",
    "Replacement Dimension",
    "unknown",
    "Replacement Dimension",
    "Dimension C-137",
    "Replacement Dimension",
    "Fantasy Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Unknown dimension",
    "Dimension K-22",
    "unknown",
    "unknown",
    "Replacement Dimension",
    "Replacement Dimension",
    "unknown",
    "Dimension D-99",
    "Dimension D716",
    "Dimension D716-B",
    "Dimension D716-C",
    "Dimension J-22",
    "Replacement Dimension",
    "Replacement Dimension",
    "unknown",
    "unknown",
    "Replacement Dimension",
    "unknown",
    "Dimension C-35",
    "Dimension C-137",
    "Pizza Dimension",
    "Phone Dimension",
    "unknown",
    "Chair Dimension",
    "unknown",
    "unknown",
    "Fascist Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Fascist Shrimp Dimension",
    "Fascist Teddy Bear Dimension",
    "Wasp Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Tusk Dimension",
    "Replacement Dimension",
    "Magic Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Merged Dimension",
    "Unknown dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Fantasy Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",
    "Replacement Dimension",

    "Replacement Dimension",
    "Replacement Dimension",
  ]),
];
